x-common: &common
  restart: unless-stopped
  networks:
    - fullstack-network
  logging: &default-logging
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
  deploy: &default-resources
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.25'
        memory: 256M

services:
  backend:
    <<: *common
    image: ${BACKEND_IMAGE}
    container_name: ${APP_NAME}_backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/var/www/html/.env
      - ./backend_data/storage:/var/www/html/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    logging:
      <<: *default-logging
      options:
        tag: "${APP_NAME}-backend"

  db:
    <<: *common
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # Backup configuration
      BACKUP_RETENTION_DAYS: 7
      BACKUP_SCHEDULE: "0 0 * * *"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s
    volumes:
      - ./db_data:/var/lib/mysql
      # Mount backup directory
      - ./backups:/backups
      # Mount backup script
      - ./db-backup.sh:/db-backup.sh
      # Mount custom entrypoint that sets up cron
      - ./db-entrypoint.sh:/custom-entrypoint.sh
    command: ["bash", "/custom-entrypoint.sh"]

  phpmyadmin:
    <<: *common
    image: phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    logging:
      <<: *default-logging
      options:
        tag: "${APP_NAME}-phpmyadmin"

networks:
  fullstack-network:
    external: true
