services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: ${APP_NAME}_backend
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_URL=http://136.244.91.127
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - storage:/var/www/html/storage
    networks:
      - fullstack-network

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fullstack-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: external

volumes:
  db_data:
  storage:
